import{S as g,a as y,i as a,b as L}from"./assets/vendor-4ea73c71.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const c=document.querySelector(".js-backdrop"),w={lines:8,length:33,width:4,radius:26,scale:.6,corners:.5,speed:1.6,rotate:0,animation:"spinner-line-fade-quick",direction:1,color:"#ffffff",fadeColor:"transparent",top:"49%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},u=new g(w),f=()=>{c.classList.remove("is-hidden"),u.spin(c)},l=()=>{c.classList.add("is-hidden"),u.stop()},d=document.querySelector(".img-container"),b="https://pixabay.com/api/",v="41741201-12a642cf53882fe64e8e82723",S=document.querySelector(".search-form"),p=document.querySelector(".js-load-morm"),m=t=>t.map(e=>`<div class="img-item">
      <a href="${e.webformatURL}" class="lightbox-link">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="image-info">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </div>`).join(""),q=(t,e)=>{e<t?p.classList.remove("is-hidden"):p.classList.add("is-hidden")},h=async t=>{try{const e=await L.get(b,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}});return e.data.total===0&&a.info({position:"center",message:"Sorry, there are no images matching your search query. Please try again!"}),e.data}catch(e){throw console.error("Error during image search:",e),new Error("Failed to retrieve images")}},k=async t=>{t.preventDefault(),f();const e=t.currentTarget.elements.query.value.trim();if(d.innerHTML="",e!=="")try{const s=await h(e);d.innerHTML=m(s.hits),new y(".lightbox-link").refresh()}catch(s){a.error({position:"center",message:"An error occurred while retrieving images. Please try again later."}),console.error("Error during search:",s)}finally{l()}else l(),a.warning({position:"center",message:"Please enter a search query."})},x=async()=>{page+=1,f();try{const{data:{results:t,totalHits:e}}=await h(query,page);d.insertAdjacentHTML("beforeend",m(t)),q(e,page)}catch(t){console.log(t)}finally{l()}};S.addEventListener("submit",k);p.addEventListener("click",x);
//# sourceMappingURL=commonHelpers.js.map
