import{S as b,a as L,i as a,b as v}from"./assets/vendor-e0a036e7.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const l=document.querySelector(".js-backdrop"),S={lines:8,length:33,width:4,radius:26,scale:.6,corners:.5,speed:1.6,rotate:0,animation:"spinner-line-fade-quick",direction:1,color:"#ffffff",fadeColor:"transparent",top:"49%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},m=new b(S),p=()=>{l.classList.remove("is-hidden"),m.spin(l)},d=()=>{l.classList.add("is-hidden"),m.stop()},u=document.querySelector(".img-container"),q="https://pixabay.com/api/",E="41741201-12a642cf53882fe64e8e82723",f=document.querySelector(".search-form"),h=document.querySelector(".js-load-more"),y=async(t,e=1,s=40)=>{try{const n=await L.get(q,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,perPage:s}});return n.data.total===0&&e===1&&(imgContainer.innerHTML="",a.info({position:"center",message:"Sorry, there are no images matching your search query. Please try again!"})),n.data}catch(n){throw console.error("Error during image search:",n),new Error("Failed to retrieve images")}},g=t=>t.map(e=>`<div class="img-item">
      <a href="${e.webformatURL}" class="lightbox-link">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="image-info">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </div>`).join(""),w=(t,e)=>{e<t?h.classList.remove("is-hidden"):(a.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),h.classList.add("is-hidden"))};let i=1;const k=async t=>{t.preventDefault(),p();const e=t.currentTarget.elements.query.value.trim();if(e!=="")try{const s=await y(e,1);u.innerHTML+=g(s.hits),new v(".lightbox-link").refresh(),w(s.totalHits,i),window.scrollBy({top:cardHeight*2,behavior:"smooth"})}catch(s){a.error({position:"center",message:"An error occurred while retrieving images. Please try again later."}),console.error("Error during search:",s)}finally{d()}else d(),a.warning({position:"center",message:"Please enter a search query."})},x=async()=>{p();try{const t=f.elements.query.value.trim(),{hits:e,totalHits:s}=await y(t,i+1);u.innerHTML+=g(e),w(s,i+1),i++;const n=u.lastElementChild.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}catch(t){console.error(t)}finally{d()}};f.addEventListener("submit",k);h.addEventListener("click",x);
//# sourceMappingURL=commonHelpers.js.map
