import{S as v,a as L,i as a,b as S}from"./assets/vendor-e0a036e7.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerpolicy&&(s.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?s.credentials="include":r.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const l=document.querySelector(".js-backdrop"),q={lines:8,length:33,width:4,radius:26,scale:.6,corners:.5,speed:1.6,rotate:0,animation:"spinner-line-fade-quick",direction:1,color:"#ffffff",fadeColor:"transparent",top:"49%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},h=new v(q),m=()=>{l.classList.remove("is-hidden"),h.spin(l)},d=()=>{l.classList.add("is-hidden"),h.stop()},f=document.querySelector(".img-container"),E="https://pixabay.com/api/",k="41741201-12a642cf53882fe64e8e82723",p=document.querySelector(".search-form"),u=document.querySelector(".js-load-more"),g=async(t,e=1,n=40)=>{try{const o=await L.get(E,{params:{key:k,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,perPage:n}});return o.data.total===0&&e===1&&a.info({position:"center",message:"Sorry, there are no images matching your search query. Please try again!"}),o.data}catch(o){throw console.error("Error during image search:",o),new Error("Failed to retrieve images")}},y=t=>t.map(e=>`<div class="img-item">
      <a href="${e.webformatURL}" class="lightbox-link">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="image-info">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </div>`).join(""),w=(t,e)=>{e<t?u.classList.remove("is-hidden"):(a.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),u.classList.add("is-hidden"))};let i=1;const b=()=>{const t=document.querySelector(".img-container").firstElementChild;return t?t.getBoundingClientRect().height:0},x=async t=>{t.preventDefault(),m();const e=t.currentTarget.elements.query.value.trim(),n=b();if(e!=="")try{const o=await g(e,1);f.innerHTML+=y(o.hits),new S(".lightbox-link").refresh(),w(o.totalHits,i),window.scrollBy({top:n*2,behavior:"smooth"})}catch(o){a.error({position:"center",message:"An error occurred while retrieving images. Please try again later."}),console.error("Error during search:",o)}finally{d()}else d(),a.warning({position:"center",message:"Please enter a search query."})},C=async()=>{m();try{const t=p.elements.query.value.trim(),{hits:e,totalHits:n}=await g(t,i+1);f.innerHTML+=y(e),w(n,i+1),i++;const o=b();window.scrollBy({top:o*2,behavior:"smooth"})}catch(t){console.error(t)}finally{d()}};p.addEventListener("submit",x);u.addEventListener("click",C);
//# sourceMappingURL=commonHelpers.js.map
